apiVersion: v1
kind: Secret
metadata:
  name: neu-aws-credentials
  namespace: neu-surface-detect
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: REPLACE_ME
  AWS_SECRET_ACCESS_KEY: REPLACE_ME
  AWS_DEFAULT_REGION: eu-west-1
